#!/bin/bash -e

name=$1
# options are range-analysis and situation drills

js_input_file='./app/'"${name}"'.js';
js_output_file='./'"${name}"'.js';

echo 'Browserifying'
node_modules/browserify/bin/cmd.js ${js_input_file} -o ${js_output_file} -t brfs --debug

scripts/build-ejs $name
scripts/build-less
