#!/usr/bin/env node

var fs = require('fs');
var less = require('less');

var less_input_path = __dirname + '/../less/main.less';
var css_output_path = __dirname + '/../index.css';
function less_to_css(cb) {
    console.log('Compiling less');
    fs.readFile(less_input_path, 'utf8', function(err, data) {
        if (err) cb(err);

        less.render(data, { filename: less_input_path }, function(err, output) {
            if (err) cb(err);

            fs.writeFile(css_output_path, output.css, function(err) {
                if (err) cb(err);
                cb();
            });
        });
    });
}

less_to_css(function(err, results) {
    if (err) {
        console.error(err);
        process.exit(1);
    }
    console.log('Done');
    process.exit(0);
});
