#!/usr/bin/env node

var ejs = require('ejs');
var fs = require('fs');

var output_path = __dirname + '/../index.html';

function ejs_to_html(path, options) {
    fs.readFile(path, 'utf8', function(err, data) {
        if (err) {
            console.error(err);
            process.exit(1);
        }

        var template = ejs.compile(data, options);
        var html = template();

        fs.writeFile(output_path, html, function(err) {
            if (err) {
                console.error(err);
                process.exit(1);
            }
            process.exit(0);
        });
    });
}

ejs_to_html(__dirname + '/../views/index.ejs', {
    filename: 'index.html'
});
